### ISSUE TITLE
Pipeline module name is too common

### ISSUE THREAD

**Issue by dionorgua** [jazzband/django-pipeline#101]
Hi,

It looks like this package module name is too common. For example there is already another package in Debian that uses "pipeline" module name:

  http://packages.debian.org/sid/python-pipeline
  http://code.google.com/p/python-pipeline/

While I understand that asking for rename is not very good thing to do, I still want to ask for some suggestions, is it possible at all, or how this can be handled other way?

**Comment by Flimm** [comment]
Debian have closed the bug report on their end, because `python-pipeline` is no longer maintained. That means we can close it here too.
