### ISSUE TITLE
Exclude files for deployment

### ISSUE THREAD

**Issue by miki725** [jazzband/django-pipeline#134]
I use `less` for my stylesheets. So obviously I use less compiler to process less files into css.

At the same time I have a group of js files where one file among them is `less.js`, which I need during development, but it is not needed in deployment.

Is there any way to exclude file(s) from a pipeline group. This way I can have the `less.js` in the group, but for deployment it will not be concatenated and compressed with the rest of the js files.

If possible, can someone describe how to do it. I can't find that in the docs. If not, then maybe to add such a feature. Maybe the possible format fo config can be be as follows:

```
PIPELINE_JS = {
    'group': {
        'source_filenames': (
            'foo1.js',
            'foo2.js',
            'foo3.js',
        ),
        'output_filename': 'foogroup.js',
        'exclude': (
            'foo2.js',
        ),
    },
}
```

**Comment by ChristopherBrix** [comment]
Has this ever been implemented? Or what's the recommended way to prevent certain files from being copied?

I'd like to exclude all test files (`filename.test.js`) while adding all other normal js files with `*.js`
