### ISSUE TITLE
Collectstatic freezes

### ISSUE THREAD

**Issue by cristiandreica** [jazzband/django-pipeline#161]
Sometimes, running python manage.py collectstatic just freezes after a couple of files (usually after 2, but sometimes after 30/40). I had this problem before and I just ran the command again. It usually worked after 2-3 attempts. Now I cannot get it to complete anymore. It just hangs after Copying 2 files...

Here is part of my configuration (staticfiles/pipeline):

``` python
STATIC_ROOT = os.path.join(PROJECT_PATH, 'tmp/static')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

INSTALLED_APPS = (
  ...
  'django.contrib.staticfiles',
  ...
  'pipeline',
)

STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'

PIPELINE_CSS_COMPRESSOR = 'pipeline.compressors.yui.YUICompressor'
PIPELINE_JS_COMPRESSOR = 'pipeline.compressors.yui.YUICompressor'
PIPELINE_YUI_BINARY = 'java -jar ' + os.path.join(PROJECT_PATH, 'external/yuicompressor-2.4.7.jar')

PIPELINE_COMPILERS = ('pipeline.compilers.less.LessCompiler',)

PIPELINE_LESS_BINARY = 'lessc'
```

Have you guys encountered this before? Any hints what I'm doing wrong?

**Comment by arvind-das** [comment]
Does it work with python3, setting PIPELINE_YUI_BINARY to java yui processor starts to compress but fails and yuicompressor from node just hungs up. Am I doing something wrong?
