### ISSUE TITLE
Concatenate files and not compress

### ISSUE THREAD

**Issue by camilonova** [jazzband/django-pipeline#173]
I have a mix of minified javascript libraries and code on my own, seems yuglify has some errors trying to minify the already minified files and minify my code.

There is a way just to concatenate the minified files, some kind of a custom compressor who can concatenate the already minified files, just to serve one file and not 5 or more?

Thanks,

**Comment by peterbe** [comment]
I don't see why this issue is closed. It's a perfectly valid issue IMHO. 

That PR is about overriding the compressor. I think it would be simply awesome to specify that something like this:
```
    'new_vendor': {
        'source_filenames': (
            'angular/angular.min.js',
            'angular/angular-sanitize.min.js',
            'angular/angular-animate.min.js',
            'angular/angular-ui-router.min.js',
            'angular/angular-moment.min.js',
        ),
        'output_filename': 'js/new-vendor.js',
        'compress': False,  # Something this simple would be nice
    },
```

**Comment by petersanchez** [comment]
I agree this is perfectly valid. This is something we actually need in a project currently (which is how I found this issue Googling for the solution)

**Comment by megahoy** [comment]
have the same problem
needs feature for concatenation already minified files
