### ISSUE TITLE
Do not create compiled JS and CSS in source directory

### ISSUE THREAD

**Issue by SoftwareMaven** [jazzband/django-pipeline#202]
If I have a file, 'foo.coffee', when I reference that file through the tag, it creates a file next to it called 'foo.js'. The problem with this is it makes it very difficult to have a version control system ignore these files.  It is very unlikely that I would want to blanket ignore .css or .js files, so that isn't an option. Instead, I'm left ignoring files individually when I add a new less or coffee file.

It would be nice if pipeline placed the files in their own directory, so I could blanket ignore that directory. As an example, if I have '{static}/foo/bar.coffee', pipeline could place the compiled file in '{static}/{pipelined}/foo/bar.js', where "pipelined" could be a configurable setting.

**Comment by kand** [comment]
@cyberdelia is there documentation on how to determine where output goes? I don't see anywhere in the current documentation that addresses this issue...

**Comment by jplehmann** [comment]
+1 for documenting this.  I spent some time this morning trying to figure this out, and am close but still not fully understanding -- my generated assets get stored in one dir when I'm using FileSystemStorage (STATIC_ROOT), which is what I want, but in my source tree when I am using s3boto-based storage.

**Comment by DelightRun** [comment]
+1
