### ISSUE TITLE
CSS non-relative imports break CSS compiler

### ISSUE THREAD

**Issue by miki725** [jazzband/django-pipeline#258]
Consider the following project layout:

```
project/
  manage.py
  project/
    settings.py
    static/
      variables.less
  app/
    models.py
    static/
      app/
        app.less
```

Then if `app.less` has the following:

```
/* app.less */
@import url("/static/variables.less")
.some-class {
    color: @variable_from_variables_less;
}
```

The above works fine if less files are directly loaded into HTML and then less compiler is run client-side because it can successfully download the `variables.less` hence resolve the variable value.

Server-side however this breaks because in order for the less compiler to compile this, it has to import the `variables.less` file. It can't do that however because the import path does not use file-system relative path (`../../project/static/variables.less`) but is instead absolute url relative to the combined static folders (once you run `collectstatic`) but that cannot be resolved because less compiler does not know about how static files will be served. Therefore the less compiler breaks because it can't figure out the variable value.

The solution is to provide less compiler with all the paths which contain static paths (`/project/project/` and `/project/app/`) which will allow it to find the needed file because it will find `/static/variables.less` in `/project/project/` which will allow it to resolve the path.

I guess similar thing can happen with other css compilers (e.g. `saass`) however I don't use them so can't tell for sure.

**Comment by mijamo** [comment]
The issue is closed but the patch hasn't been merged yet. It is planned to do so soon or is there any problem with it ?

It works fine for me with the patch, but without it fails (with v 1.4.7).

**Comment by jjmurre** [comment]
I came across a similar problem. Solved it with lessc cli arguments in setting.py::

in BOWER_COMPONENTS there is a 'bootstrap' folder

    BOWER_COMPONENTS = os.path.join(PROJECT_DIR, '..',  'bower_components') 
    PIPELINE_LESS_ARGUMENTS = '--include-path="{}"'.format(BOWER_COMPONENTS)

Now in my lessfile I can just:

    @import "bootstrap/less/bootstrap.less"
