### ISSUE TITLE
How to do a S3 + Cached + GZipped storage class?

### ISSUE THREAD

**Issue by gtaylor** [jazzband/django-pipeline#339]
Here is my current attempt, with DEBUG=False:

```python
from django.contrib.staticfiles.storage import CachedFilesMixin, \
    StaticFilesStorage
from django.conf import settings

from pipeline.storage import PipelineMixin, GZIPMixin

from storages.backends.s3boto import S3BotoStorage
class S3PipelineStorage(PipelineMixin, CachedFilesMixin, GZIPMixin, S3BotoStorage):
    bucket_name = settings.PIPELINE_S3_BUCKET
    auto_create_bucket = True
    preload_metadata = True
    querystring_auth = False
    url_protocol = 'https:'
    gzip = True
```

However, when I collectstatic, I don't see any gzipping happening. When I check the rendering on the app server, no .gz suffixes are appearing, either.

I suspect this is a question of getting the right order and mixins. Am I missing something?

Not sure if this is relevant, but I also have the following STATICFILES_FINDERS specified on the production server:

```python
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)
```

Wasn't sure if that last one was needed with the S3 backend.

**Comment by cyberdelia** [comment]
You can eventually give this branch a try for returning gzip URL: https://github.com/cyberdelia/django-pipeline/tree/gzip-url

**Comment by cyberdelia** [comment]
Whitenoise and other web server will server the .gz file when available. No need for pipeline to handle this case.
