### ISSUE TITLE
File references in javascript

### ISSUE THREAD

**Issue by snoepkast** [jazzband/django-pipeline#364]
Hi,

While using the cached file storage it's still very simple in css to point to another css file by using ` url(filename)` as normal and the filename will be replaced with the cached filename.

But how do I do this in javascript?

For example, bootstrap-wysihtml5 requires that you give a [valid path](https://github.com/jhollingworth/bootstrap-wysihtml5/blob/master/src/bootstrap-wysihtml5.js#L453) to a stylesheet to be inserted in the iframe that will be generated.

**Comment by cyberdelia** [comment]
URL rewriting is done by staticfiles, and only support CSS. You might be able to inject the correct path using statifciles helpers.
