### ISSUE TITLE
Pipeline does not work under Windows

### ISSUE THREAD

**Issue by SaulTigh** [jazzband/django-pipeline#368]
So, the problem is that, when I use collectstatic, output files are created empty under windows.

The configuration I use is:

     STATICFILES_DIRS = (
        ('js', os.path.join(PROJECT_ROOT, 'coffee')),
        ('css', os.path.join(PROJECT_ROOT, 'less')),
        ('font', os.path.join(PROJECT_ROOT, 'font')),
        ('images', os.path.join(PROJECT_ROOT, 'images')),
        ('img', os.path.join(PROJECT_ROOT, 'img')),
    )

    STATICFILES_FINDERS = (
        "django.contrib.staticfiles.finders.FileSystemFinder",
        "django.contrib.staticfiles.finders.AppDirectoriesFinder",
        'pipeline.finders.PipelineFinder',
    )

    # Pipeline Configuration
    STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'
    PIPELINE_CSS_COMPRESSOR = None
    PIPELINE_JS_COMPRESSOR = None
    PIPELINE_COMPILERS = (
        'pipeline.compilers.coffee.CoffeeScriptCompiler',
        'pipeline.compilers.less.LessCompiler',
    )
    PIPELINE_COFFEE_SCRIPT_ARGUMENTS = '-m'  # -b
    PIPELINE_LESS_ARGUMENTS = '-x'
    PIPELINE_CSS = {
        'style': {
            'source_filenames': (
                'css/style.less',
            ),
            'output_filename': 'css/style.css',
        },
    }
    PIPELINE_JS = {
        'common': {
            'source_filenames': (
                'js/app.coffee',
                'js/index.coffee',
                'js/catalog.coffee',
                'js/blog.coffee',
                'js/about.coffee',
                'js/delivery.coffee',
                'js/constructor.coffee',
            ),
             'output_filename': 'js/common.js',
        }
    }
    PIPELINE_DISABLE_WRAPPER = True

And it's worth to mention that with this configuration pipeline works fine under Ubuntu.

**Comment by cyberdelia** [comment]
Can't really reproduce, hopefully, recent work should have improve our window support.
