### ISSUE TITLE
SemVer

### ISSUE THREAD

**Issue by doismellburning** [jazzband/django-pipeline#393]
I'd love it if you used [Semantic Versioning](http://semver.org/) please.

Specifically, if you could bump the _major_ version number when you make incompatible API changes, [like the ones made in the 1.4 release](https://github.com/cyberdelia/django-pipeline/blob/1.4.0/docs/installation.rst#upgrading-to-14)

Cheers

**Comment by pquentin** [comment]
(For what it's worth, I personally prefer the way django handles incompatible changes.)
