### ISSUE TITLE
Bad Request (400) for subfolders

### ISSUE THREAD

**Issue by thekensman** [jazzband/django-pipeline#402]
Hi,

After specifying a subfolder under static for a group of scripts in PIPELINE_CSS I get a 400 error when trying to access a page where the group is loaded. However, moving the files to the top level of the static directory and taking out the subfolder in the setting gets rid of the error.

Setting that gives an error:

``` python
PIPELINE_CSS = {
    'master': {
        'source_filenames': (
            'sass/master.sass'
        ),
        'output_filename': 'css/master.css',
    },
}
```

Setting that works:

``` python
PIPELINE_CSS = {
    'master': {
        'source_filenames': (
            'master.sass'
        ),
        'output_filename': 'css/master.css',
    },
}
```

Any idea what might cause this?

**Comment by sikko** [comment]
Very odd indeed! Solved my problem! thank you!
