### ISSUE TITLE
{% stylesheet 'foo' %} silently fails even with DEBUG=True

### ISSUE THREAD

**Issue by leo-the-manic** [jazzband/django-pipeline#413]
I wish I had more specific info, but essentially, I'm using `{% stylesheet 'foo' %}` and nothing comes out in my markup, and no loggers show anything.

My logging config:

```python
LOGGING = {
    'version': 1,

    'formatters': {
        'console': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },

    },

    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    },
}
```

My static files settings...

```python
STATIC_ROOT = os.path.join(BASE_DIR, "static_build")

STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)

PIPELINE_COMPILERS = (
    'pipeline.compilers.sass.SASSCompiler',
)
```

My pipeline files config...

```
PIPELINE_CSS = {

    'foo': {
        'source_filenames': (
            'main/css/foo.sass',
        ),
        'output-filename': 'main/css/foo-sass.css',
    },

}
```

Running Python 3.4.0 on Windows 7 with Django 1.7 and django-pipeline version 1.4.3. Sorry this is kind of sparse; I am trying to get the ball rolling on a project and gotta get back to doing more project specific things. So I thought I'd cobble together a 'bug report' as quick as possible to see if this is actually a known issue; otherwise I'll spend some time later coming up with an easier to use Github mini-project to showcase the bug/issue.

To be fair I'm not sure if this is a 'bug' or intentional (and if so, pointlessly hard to use) design; for some reason '{% stylesheet 'foo' %}' is leaving nothing in my markup and emitting no log messages in spite of me having `settings.DEBUG == True`. This is effectively stopping me from using Sass in a clean way with my current project.

**Comment by bardo** [comment]
Same problem on django-pipeline 1.4.3, Django 1.6 and Python 2.7.9 on Linux.

**Comment by dobestan** [comment]
Same problem on django-pipeline 1.4.6, Django 1.7 and Python 2.7.9

**Comment by Conlectus** [comment]
Same problem on django-pipeline 1.4.6, Django 1.7.4, Python 2.7.8

**Comment by gabrielvdk** [comment]
I found out the issue for me was that one of the paths of the source files was incorrect. 

Would be better if you get some sort of indication of that (i.e. include everything but that file / render a HTML comment telling about the issue / give a 404 with explanation).

**Comment by spectras** [comment]
I have the same issue.
From what I investigated so far, it looks things somehow get mixed up on pipeline 1.4, and pipeline tries to look for source files in the `staticfiles_storage`. That is incorrect, as this place should only have final files.

I have the same issue when running `./manage collectstatic`. Package files get generated empty unless I also include their sources. For the very same reason: pipeline's `glob` function will look for source files in the target directory.
