### ISSUE TITLE
compilers using pipes.quote() == not Windows compatible. breaks LESSc

### ISSUE THREAD

**Issue by wahuneke** [jazzband/django-pipeline#444]
In bug #335, a call to quote() was added to better handle variety of filenames. It turns out that quote() is not windows compatible and is not intended to be (neither the shlex version nor the pipes version).

quote() adds single quote characters, windows requires double quotes as single quotes have no special meaning (to windows it's just an apostrophe, and apostrophes are ok in windows filenames).

For me, pipeline is adding single quotes everywhere it calls lessc. This is breaking lessc, which does not handle the single quotes properly. It tries to add the current working directory to the quoted filename and comes up with a brand new filename that is not valid.

To me, things would be much simpler if you called lessc using Popen in 'not shell' mode. Pass in the name of the executable, pass in the arguments as an array. Dont try to quote anything. dont turn the whole thing into one long command string. Is there a reason it was not implemented this way?

I have already been working with lessc. They merged a patch for me which "fixes" the single quote issue. But now we are removing it because it breaks to deviate from the windows specs in this way.

I can submit a PR, just wanted to get feedback first if possible.

wonder if this is related to issue #368 ...

**Comment by dwatkinsweb** [comment]
I am getting this same issue and was just about to try and figure out a resolution myself. If you have one I recommend setting a pull request and I can help test as well. Otherwise, I can assist in resolving this issue if needed.

**Comment by wahuneke** [comment]
Yeah, I played around with solutions a while back. Wound up rewriting
things so that lessc, et al no longer would execute in shell mode.
Eventually figured out that this is not ideal because those guys actually
tend to be shell scripts and everything's just a heck of a lot easier if we
execute in shell mode.

Backing that change out, I still did have a solution that removed the
quoting. I will get that pushed as a PR, but probably can't get to that
today.
