### ISSUE TITLE
pipeline + slimit breaks moment-timezone-with-data.js

### ISSUE THREAD

**Issue by brianmay** [jazzband/django-pipeline#445]
As downloaded from http://momentjs.com/downloads/moment-timezone-with-data.js

It contains the following code:

```js
for (i; i < whole.length; i++) {
        num = charCodeToInt(whole.charCodeAt(i));
        out = 60 * out + num;
}
```

This gets turned into:

```js
for(ii<whole.length;i++){num=charCodeToInt(whole.charCodeAt(i));out=60*out+num;}
```

i.e. the semicolon got dropped from "i;" in the loop expression.

Just running slimit on the file by itself seems to be ok. If I turn off slimit in pipeline, it is ok too. If I change the value to "dummy=0", it works fine.

Apologies if this is actually a slimit bug, finding it hard to try and diagnose. I suspect pipeline is doing some sort of post-processing on the file and messing things up.

**Comment by cyberdelia** [comment]
Sounds like a limit problem here. Sorry.

**Comment by brianmay** [comment]
... except it doesn't happen if I test slimit standalone. It only happens if I use slimit with django-pipeline. Any ideas why?
