### ISSUE TITLE
How to use pipline with Jinja2

### ISSUE THREAD

**Issue by intotecho** [jazzband/django-pipeline#458]
I am trying to understand how to use pipeline in a jinja2 gae project.

"Unlike the Django template tag implementation the Jinja2 implementation uses different templates, so if you wish to override them please override pipeline/css.jinja and pipeline/js.jinja."

But I don't understand the syntax well enough. The following line from the docs suggests a different syntax. Are there any examples, or test cases of using jinj2 template with django-pipeline?

This is a documentation request. I have posted a related question on Stack Exchange.
http://stackoverflow.com/questions/30325130/how-to-call-django-pipeline-compressor-with-jinja2-templates

**Comment by cyberdelia** [comment]
@intotecho It also depends on your Django version, since Django now allow multi-templating engines.

**Comment by cyberdelia** [comment]
I believe you had your answer over at stackoverflow, it also match the current documentation: http://django-pipeline.readthedocs.org/en/latest/usage.html#jinja
