### ISSUE TITLE
Don't check to see if a source file exists

### ISSUE THREAD

**Issue by ryanmcgrath** [jazzband/django-pipeline#466]
Hi there,

I've got a lot of love for this project, but one incredibly confusing thing is the following: why does Pipeline need to confirm a file exists? Just let any compilation/etc error out naturally; by checking for the existence of files before (packager.py:lines ~26-30) you make it so certain things won't get pulled in some scenarios.

e.g, I don't want to have to run `collectstatic` every time I wanna reflect a change. With what Packager currently does, it checks to see if the file exists inside the static root, but in development it _should_ be checking all the relevant static paths. This incredibly basic not ideal patch to Packager shows what I'm talking about:

``` python
class Package(object):
    def __init__(self, config):
        self.config = config
        self._sources = []

    @property
    def sources(self):
        if not self._sources:
            paths = []
            for pattern in self.config.get('source_filenames', []):
                paths.append(pattern)  # Don't bother checking for existence
                #for path in glob(pattern):
                #    if path not in paths and find(path):
                #        paths.append(str(path))
            self._sources = paths
        return self._sources
```

This makes Pipeline just load things in development with no issues at all. There's likely a better patch for it but I've not got the time to dig into it, just wanted to leave a note for anyone else confused by it.

**Comment by cyberdelia** [comment]
I'm not sure that this would work for prefixed staticfiles configuration.
Are you using the most recent version of pipeline? Development compilation has been reduce in recents versions.
