### ISSUE TITLE
google pagespeed insights bad score

### ISSUE THREAD

**Issue by mirzadelic** [jazzband/django-pipeline#493]
I need to fix following:
 - Enable compression (can save 74% reduction)
 - Eliminate render-blocking JavaScript and CSS in above-the-fold content
 - Minify JavaScript (can save 3% reduction)
 - Minify CSS (1% reduction)

i use pipeline, so why google is showing me that.
How can make optimisation better?

my config:
```
STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
PIPELINE_CSS_COMPRESSOR = 'pipeline.compressors.yuglify.YuglifyCompressor'
PIPELINE_JS_COMPRESSOR = 'pipeline.compressors.yuglify.YuglifyCompressor'
```
[Check PageSpeed of my website]
(https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.oglasise.com%2F)

**Comment by cyberdelia** [comment]
This is outside of pipeline scope, you might want to ask for help elsewhere, or hire an expert.
Sorry.
