### ISSUE TITLE
Document manifesto integration better.

### ISSUE THREAD

**Issue by skorokithakis** [jazzband/django-pipeline#508]
The documentation on manifesto is very sparse. I've added the library but there's no way for me to check whether it's working, and I suspect it's not.

**Comment by skorokithakis** [comment]
For anyone having the same problem as me, and to save people an hour of frustration:

The documentation is incomplete. It is **not** enough to include the `manifesto` app, you also need to add the URL and link to it in your template. Basically, you need to completely set up `manifesto`, except you don't need to specify where it will find the static files.

@cyberdelia, please update the documentation to save others the frustration.

**Comment by peymanslh** [comment]
As for #783, we decided to drop support for the manifesto package.
So I close issues related to it.
