### ISSUE TITLE
Version 1.6.0 should probably be 2.0.0

### ISSUE THREAD

**Issue by slafs** [jazzband/django-pipeline#515]
Just wanted to point that out, since Jazzband states about BREAKING.FEATURE.FIX release numbering (https://jazzband.co/docs/releases), django-pipeline 1.6 should probably be released as 2.0, because of the breaking change in how to configure it (i.e. `PIPELINE` dict setting). In other words, user can't just bump version number of django-pipeline (from 1.5.x to 1.6) without changing the code (configuration). Although I'm glad that this is documented (http://django-pipeline.readthedocs.org/en/latest/installation.html#upgrading-from-1-5), thanks.

**Comment by cyberdelia** [comment]
Historically, pipeline increase the equivalent FEATURE version, with every Django new version.
1.6 was mostly developed before the jazzband move, so some people were expecting a 1.6 more than a 2.0.

So maybe 2.0 will be the new 1.7.

**Comment by slafs** [comment]
> 1.6 was mostly developed before the jazzband move, so some people were expecting a 1.6 more than a 2.0.

Oh, didnt think about that. Thanks for the explanation.
