### ISSUE TITLE
Permission denied if shell=False

### ISSUE THREAD

**Issue by eugene-eshengulov** [jazzband/django-pipeline#524]
Permission denied error occurs on 'manage.py collectstatic' execution
[-shell=True] (https://github.com/jazzband/django-pipeline/commit/9be0f2934667d0fc199fac30e6f9a0e7115888ec#diff-fde7a3bb47631ce4a4007fb9d5b36927L246)

**Comment by cyberdelia** [comment]
This is lacking some useful details, but could you check if the script/binary you are calling is actually executable? (+x)

**Comment by eugene-eshengulov** [comment]
Sorry, after reboot I can't reproduce. Most likely the problem was unrelated to the commit.
