### ISSUE TITLE
Django 1.7: cannot import name setting_changed

### ISSUE THREAD

**Issue by davneet4u** [jazzband/django-pipeline#529]
While running django-pipeline 1.6.4 with django 1.7, I get this error "TemplateSyntaxError: 'pipeline' is not a valid tag library: ImportError raised loading pipeline.templatetags.pipeline: cannot import name setting_changed" .

I noticed the problem is here 
/env/local/lib/python2.7/site-packages/pipeline/conf.py in <module>()
      6 
      7 from django.conf import settings as _settings
----> 8 from django.core.signals import setting_changed
      9 from django.dispatch import receiver
     10 from django.utils.six import string_types

I saw this documentation https://docs.djangoproject.com/en/1.9/ref/signals/#setting-changed and notice that it is django.test.signals.setting_changed in Django 1.7, until it was changed in Django 1.8

How do I go about it?

**Comment by pacahon** [comment]
Try to use previous version. Django 1.7 is not supported since `django-pipeline 1.6` as I can see in changelog.
https://github.com/jazzband/django-pipeline/blob/master/HISTORY.rst#160

Someone should update docs I guess.

**Comment by davidt** [comment]
This was fixed by https://github.com/jazzband/django-pipeline/pull/536
