### ISSUE TITLE
How to use pipeline with: DEBUG=TRUE and PIPELINE_ENABLED: True

### ISSUE THREAD

**Issue by sowinski** [jazzband/django-pipeline#577]
Hi,

pipeline is doing a good job, but I would like to enable pipeline while I am developing.
If I turn DEBUG=True und PIPELINE_ENABLED = True I can not access my static_files.

**Comment by devsnd** [comment]
I am currently seeing the same issue. This seems to be a duplicate of #487 however.

**Comment by devsnd** [comment]
BTW: I have implemented a simple workaround for this issue, see #487 for details.

**Comment by bashu** [comment]
same issue

**Comment by Flimm** [comment]
@sowinski This looks like it's a duplicate of #487.
