### ISSUE TITLE
Deprecation warnings on Django 1.10

### ISSUE THREAD

**Issue by anderspetersson** [jazzband/django-pipeline#586]
> pipeline/collector.py:68: RemovedInDjango20Warning: FileSystemStorage.modified_time() is deprecated in favor of get_modified_time().

> pipeline/collector.py:75: RemovedInDjango20Warning: FileSystemStorage.modified_time() is deprecated in favor of get_modified_time().

How do we preserve backwards compatibility?

**Comment by malefice** [comment]
My [PR](594) should fix this. I hope more people can test for Django 1.10 compatibility.

**Comment by anderspetersson** [comment]
Thanks,

Since that PR got merged I'm closing this.
