### ISSUE TITLE
Broken wheel for 1.6.11?

### ISSUE THREAD

**Issue by pacahon** [jazzband/django-pipeline#616]
Hello, I guess something wrong with `1.6.11` wheel. 
I've just installed `1.6.11` with pip (on mac system if it matters) and got dependency issue like below
```
File "/Users/pacahon/.pyenv/versions/csc/lib/python3.4/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
```

After some investigation, I mentioned this:
```
$ pip -V
pip 9.0.1 from /Users/pacahon/.pyenv/versions/test_env/lib/python3.4/site-packages (python 3.4)
$ pip install -vvv django-pipeline
...
Downloading from URL https://pypi.python.org/packages/4d/63/1c7e2d78a20986a09d37df176f5902b1b6bd7d6ce13177e3180ea8f11724/django_pipeline-1.6.11-py2.py3-none-any.whl#md5=21231243e71400d7cb315df257bafcad (from https://pypi.python.org/simple/django-pipeline/)
Collecting futures>=2.1.3 (from django-pipeline)
...
Successfully installed django-pipeline-1.6.11 futures-3.0.5
```

pip trying to install `futures` package which is backport for py2.
P.S `1.6.10` works just fine. No `futures` among successfully installed packages.
P.P.S Screenshot from pypi (look at wheel name and then "Py version"
<img width="892" alt="screen shot 2017-02-06 at 20 48 19" src="https://cloud.githubusercontent.com/assets/460489/22659180/b99186f6-ecad-11e6-8d01-da66bcb65d20.png">

**Comment by scottwoodall** [comment]
I noticed this as well. I'm using Python 3.4.3 and was receiving the same error as @pacahon on pipeline version 1.6.11. Downgrading to 1.6.10 resolved the exception.

If I'm reading`setup.py` right `futures` shouldn't be getting installed on python 3.4.3.

**Comment by km-pg** [comment]
same here

**Comment by Flimm** [comment]
I assume you folks still experience the issue with django-pipeline 1.6.12?

https://pypi.python.org/pypi/django-pipeline

**Comment by pacahon** [comment]
@Flimm Works fine for me with `1.6.12`. I guess I should close this issue.
