### ISSUE TITLE
With Django 1.11 files get post-processed multiple times

### ISSUE THREAD

**Issue by belugame** [jazzband/django-pipeline#650]
On Django 1.11 I see pipeline post-process the same file to the same hashed version multiple times and in the end I have 2 different files e.g.

```
media/admin.min.70004aec9612.css
media/admin.min.3719a5a090af.css

```
That does not happen on Django <1.10 

example snippet of a my config:
```
         'admin_min_css': {                                             
                'source_filenames': (                                      
                'js/libs/chosen/chosen.css',                           
            ),                                                         
            'output_filename': 'admin.min.css',                        
         },
```

Anyone else experiencing that? Possibly related to the introduction of storage.ManifestStaticFilesStorage.max_post_process_passes in 1.11

**Comment by czubik8805** [comment]
I confirm this error with Django 1.11.10. I see pipeline post-process the same file multiple times.

```
Post-processed 'bower_components/bootstrap/dist/css/bootstrap.css' as 'bower_components/bootstrap/dist/css/bootstrap.60711a51db5e.css'
Post-processed 'bower_components/bootstrap/dist/css/bootstrap.css' as 'bower_components/bootstrap/dist/css/bootstrap.cb8a77bb5700.css'
Post-processed 'bower_components/bootstrap/dist/css/bootstrap.css' as 'bower_components/bootstrap/dist/css/bootstrap.3c7be87695cb.css'
```

after a while, this error comes up:
```
Post-processing 'All' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/karten_stage/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
    raise processed
RuntimeError: Max post-process passes exceeded.

```

I use S3BotoStorage.

**Comment by bitcity** [comment]
Turns out it's a bug in Django 1.11 

[HashedFilesMixin's post_process() yields multiple times for the same file](https://code.djangoproject.com/ticket/28607
)

[https://code.djangoproject.com/ticket/28604](https://code.djangoproject.com/ticket/28604)

**Comment by belugame** [comment]
@bitcity  Sorry I dont remember what I did about it, or if I just accepted it as it did not break things.

**Comment by czubik8805** [comment]
I temporarily used CachedStaticFilesStorage instead of ManifestStaticFilesStorage, it works for me.

**Comment by hsiaoyi0504** [comment]
I am going to close this, because it seems to be the bug of django. It can be re-open later.

**Comment by DrMeers** [comment]
When using S3 if query-string authentication is enabled, you can end up in a situation where CSS files contain URLs with query-string parameters such as `AWSAccessKeyId=...&Signature=...=&Expires=...` -- and each time each file is hashed, these can change, creating an endless loop of differing hashes. Turing `AWS_QUERYSTRING_AUTH` off might help.
