### ISSUE TITLE
Django 2.2 Support

### ISSUE THREAD

**Issue by auvipy** [jazzband/django-pipeline#692]

**Comment by hugokernel** [comment]
Hi,
Any news about Django 2.2 support ?
Thx

**Comment by auvipy** [comment]
please check the master branch

**Comment by chrisspen** [comment]
It works for me in Django 2.2 if I patch/override PipelineFinder like I describe in #699.

**Comment by eire1130** [comment]
@auvipy hello, there's a PR here that will allow for django 3.0 support.
https://github.com/jazzband/django-pipeline/pull/708
 Would be useful for me to have that looked into, this is the last package blocking us from upgrading to django3.0

**Comment by TheBuky** [comment]
Can we close this issue if the support was been done for Django 2.2?
