### ISSUE TITLE
Disable MIMETYPES

### ISSUE THREAD

**Issue by vonmaster** [jazzband/django-pipeline#695]
Hi,

Thank you for this useful library.

I was wondering if it was possible to **disable mimetypes**. According to the W3C Markup Validator :
> the `type` attribute is unnecessary for JavaScript resources;
> the type attribute for the `style` element is not needed and should be omitted.

Basically, I just want to replace `<script type="text/javascript" src="/static/js/script.js" charset="utf-8"></script>` by  `<script src="/static/js/script.js"></script>`.

I tried to override `PIPELINE_MIMETYPES` but it does not work.

**Comment by vonmaster** [comment]
Please, can someone tell me who is maintaining this repository?

**Comment by jankyupeblik** [comment]
The simplest way to accomplish this at the moment is to provide your own duplicate of the provided `js.html` template and include `'template_name':'path/to/type-less-js.html',` in your pipeline configuration.  
https://django-pipeline.readthedocs.io/en/1.6.14/configuration.html  
https://django-pipeline.readthedocs.io/en/1.6.14/configuration.html#template-name

As for improving the software...

While one could make the argument for special situations that might still merit the inclusion of `type="text/javascript"` or the like for JavaScript, this package really doesn't fulfill so many roles at the moment as it is, which makes me think altering the provided template would also be a suitable "long term" solution.

Aside from merely altering the provided template, it would also be fairly straightforward a modification to allow `type` to be available as an `extra_context` switch.

**Comment by vonmaster** [comment]
Thank you for your thorough explanation. Your solution worked like a charm. To me, the documentation is not clear enough regarding this.

**Comment by jankyupeblik** [comment]
I guess if you keep the filename the same you won't strictly need to add the `'template_name':'path/to/type-less-js.html'`, even.
