### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by jesusch** [jazzband/django-pipeline#702]
last tag is from Jan 2018
there had been several commits/fixes since then

**Comment by TheBuky** [comment]
In view of the time elapsed since the last tag, I decided to create one on the upper major version. @jesusch, I have just released [1.7.0](https://github.com/jazzband/django-pipeline/releases/tag/1.7.0) which should work with Django 3.0. Can I close this issue?

**Comment by jesusch** [comment]
If we get this to pypi then I'm happy 🤩

Buky <notifications@github.com> schrieb am Do., 26. Dez. 2019, 18:54:

**Comment by TheBuky** [comment]
@jesusch I just push the release on PyPI. It will be available soon.

_Nb:_ I just forget to update the file `HISTORY.rst` display on [PyPI](https://test.pypi.org/project/django-pipeline/).

Enjoy

**Comment by cyberdelia** [comment]
I manually released 1.7.0, while we figure out how to fix the travis build.
