### ISSUE TITLE
Django 3 dropped support to django.utils.six

### ISSUE THREAD

**Issue by TheBuky** [jazzband/django-pipeline#707]
I just try to upgrade my server to [Django 3.0](https://docs.djangoproject.com/en/3.0/releases/3.0/) release today for tests and as we can read the module django.utils.six will be dropped with the version 3 of Django.

Here you can find my Traceback:
```python
  File "/home/user/.virtualenvs/dns/lib/python3.7/site-packages/pipeline/finders.py", line 9, in <module>
    from pipeline.conf import settings
  File "/home/user/.virtualenvs/dns/lib/python3.7/site-packages/pipeline/conf.py", line 15, in <module>
    from django.utils.six import string_types
ModuleNotFoundError: No module named 'django.utils.six'
```
Please evaluate the migration to six as suggested in the #removed-private-python-2-compatibility-apis section of the release note.

Thanks for this amazing library!

**Comment by TheBuky** [comment]
As well you can replace `string_types` in `pipeline/conf.py` line `101` by `(str,)`?

```python
In [1]: from django.utils.six import string_types

In [2]: string_types
Out[2]: (str,)

In [3]: string_types == (str,)
Out[3]: True
```

**Comment by phaneendrahari** [comment]
This is an amazing library. Looking forward to the fix for Django 3.0.0

**Comment by TheBuky** [comment]
The concept for `metaclass` is really different between python 2 and 3 (more than I thought) for `PipelineFormMedia`... 

We have two choices:
1. Dropping Python 2 support and the Python 3 use modern syntax: `class PiepelineFormMedia(object, metaclass=PipelineMediaMetaClass)`
2. Copy the `django.utils.six` decorator to reuse it.

**Comment by TheBuky** [comment]
Merge request #708 fix this

**Comment by eire1130** [comment]
@TheBuky Thanks for getting this merged. Do you have a sense on when this will be available on pypi? We still need to point directly to repo rather then just `pip install django-pipeline==1.7.0 --upgrade`

**Comment by TheBuky** [comment]
@eire1130 The Travis job to automatically publish package and PyPI.org is broken (authentication error). I open an issue to [Jazzband](https://jazzband.co/about) for checking the credentials, and fix it.

Meanwhile you can, you can `git clone` the project, go in the `django-pipeline` repertory and do `python3 setup.py sdist bdist_wheel`. That will create new folder *dist* and you can install the package with `pip install -U dist/django-pipeline-1.7.0.tar.gz` (or something like that). 
Like explained [there](https://packaging.python.org/tutorials/packaging-projects/)

**Comment by eire1130** [comment]
@TheBuky thanks. I just need it to live in my requirements.txt for deploys. For now I have it pinned source, which works of course, but I prefer to use package / pypi names rather then pointing to github.

Again, thank you for being on top of this, I really appreciate it!
