### ISSUE TITLE
MutableMapping should be imported from collections.abc

### ISSUE THREAD

**Issue by colons** [jazzband/django-pipeline#712]
The `MutableMapping` import in `conf.py` warns: `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working`

Are there any compatibility reasons not to change this?

**Comment by TheBuky** [comment]
Will be resolved in version 2.0.3. Upgrade to the last version.
