### ISSUE TITLE
Django 3.1 dropping CachedStaticFilesStorage

### ISSUE THREAD

**Issue by brianmay** [jazzband/django-pipeline#714]
RemovedInDjango31Warning: CachedStaticFilesStorage is deprecated in favor of ManifestStaticFilesStorage.

Setting `STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'` appears to be the cause here.

**Comment by TheBuky** [comment]
#711 will resolve the problem. Maybe this will be great to add documentation for this

**Comment by TheBuky** [comment]
Will be resolved in version 2.0.3. Upgrade to the last version.

**Comment by vmsp** [comment]
`CachedStaticFilesStorage` is no longer available in Django 3.1. Maybe a guard could be put around the import?

**Comment by TheBuky** [comment]
Django-pipeline v2.0.5 will resolv this issue

**Comment by mprat** [comment]
I've upgraded to version 2.0.7 but I am still getting this deprecation error with Django 2.2. Any hints?
