### ISSUE TITLE
Non-matching release notes for 2.0.3

### ISSUE THREAD

**Issue by amrishparmar** [jazzband/django-pipeline#722]
The release note description for 2.0.3 seems to differ on https://github.com/jazzband/django-pipeline/releases/tag/2.0.3 when compared with https://github.com/jazzband/django-pipeline/blob/master/HISTORY.rst

There are 7 items in the former, whereas there is only 1 in the latter currently.

**Comment by TheBuky** [comment]
Yeah, I know. I was bored to manually create releases :D 
So I have stacked versions **2.0.2** and **2.0.3** (who just include a minor improvement in `setup.py`), and you can see there is another history on [Pypi](https://pypi.org/project/django-pipeline/#history)... Don't blame me.

The **Travis job**, who normally automatically create Github releases, Pypi packages and publish doc is broken (related [issue](https://github.com/jazzband-roadies/help/issues/177)). We have to do it manually until it gets fixed, so I take the time to make the major versions.
