### ISSUE TITLE
K

### ISSUE THREAD

**Issue by mayurn12** [jazzband/django-pipeline#724]
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from .forms import PatientSignUp, OPD_MemberSignUp, DoctorSignUp
from django.contrib.auth.forms import AuthenticationForm
from .models import User

def Home(request):
    return render(request,'home.html')

def register(request):
    return render(request,'register.html')

class patient_register(CreateView):
    model = User
    form_class = PatientSignUp
    template_name = 'patient_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

class doctor_register(CreateView):
    model = User
    form_class = DoctorSignUp
    template_name = 'doctor_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

class opd_register(CreateView):
    model = User
    form_class = OPD_MemberSignUp
    template_name = 'opd_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, 'login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')

# and in template showing 
![template](https://user-images.githubusercontent.com/63412610/89715126-4c492900-d9c1-11ea-858e-888c32c8bbe7.png)

# my urls

from django.urls import path
from .import views

urlpatterns = [
    path('',views.Home,name="home"),
    path('register/',views.register,name="register"),
    path('patientregister/',views.patient_register,name="patientregister"),
    path('doctorregister/',views.doctor_register,name="doctorregister"),
    path('opdregister/',views.opd_register,name="opdregister"),
    path('login/',views.login_request, name='login'),
    path('logout/',views.logout_view, name='logout'),

]

**Comment by kawa-marcin** [comment]
@mayurn12 Please close this issue. It has nothing to do with the `django-pipeline` for any issues related to Django or python visit [StackOverflow](https://stackoverflow.com/).

Anyway, your problem is probably related to the `DoctorSignUp` form which you have not posted here. You're probably overwriting the `__init__` method ...

Good luck with your Django adventure ;)
