### ISSUE TITLE
Removes deprecation warning for Django in signals.py

### ISSUE THREAD

**Issue by tsabat** [jazzband/django-pipeline#728]
When `signals.py` is used in a django project, we get the following warning

```app\venv\lib\site-packages\pipeline\signals.py:5: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.```

I'm removing this to stop the noise.

https://github.com/jazzband/django-pipeline/pull/727

**Comment by TheBuky** [comment]
Fix was merged
