### ISSUE TITLE
HTML minification issue: <pre> tags should not be minified

### ISSUE THREAD

**Issue by nemesisdesign** [jazzband/django-pipeline#744]
Removing whitespace within `<pre>` tags doesn't look right because it basically breaks text which was formatted using, spaces, tabs and line breaks.

Eg:

![Screenshot from 2021-01-21 12-58-30](https://user-images.githubusercontent.com/841044/105391880-90835b00-5be8-11eb-8d9d-570c184f98f6.png)

Is this a problem of django-pipeline or of one of its dependencies?

**Comment by pandafy** [comment]
django-pipeline uses `django.utils.html.strip_spaces_between_tags` to [minify HTML](https://github.com/jazzband/django-pipeline/blob/master/pipeline/middleware.py). And [`strip_spaces_between_tags`](https://github.com/django/django/blob/a736baab92acb26eab09979143b2eafb53b957dd/django/utils/html.py#L194-L197) uses regex to remove spaces between tags. It is not intelligent enough to know from where it is removing space.

**Comment by nemesisdesign** [comment]
Upon further investigation, I understood that my understanding of what was going on was not 100% correct.
Space is stripped between tags. If `<pre>` contains HTML tags as in the case of Django REST Framework, the whitespace is removed, eg:

```html
<pre>
   <b>HTTP 200 OK</b>
   <b>Allow:</b> <span>GET, HEAD, OPTIONS</span>
</pre>
``` 

Becomes:

```
<pre>
   <b>HTTP 200 OK</b><b>Allow:</b> <span>GET, HEAD, OPTIONS</span>
</pre>
``` 

We handled this with CSS. I am not sure there's a simple way to handle this with regexp.
I am closing this issue for now as I doubt is worth fixing in this library.
