### ISSUE TITLE
Not support Django 4.0

### ISSUE THREAD

**Issue by markflorence728** [jazzband/django-pipeline#766]
https://docs.djangoproject.com/en/4.0/releases/4.0/#:~:text=django.utils.encoding.force_text()%20and%20smart_text()%20are%20removed.

https://github.com/jazzband/django-pipeline/blob/86283262bbbeb9c55bbf265456c8444a122c681a/pipeline/compressors/__init__.py#L10
There is an invalid function that is removed in django4.0..
We must replace django.utils.encoding.force_text() to django.utils.encoding.force_str()

Hope to see a fast upgrade for django4.0 support

**Comment by kevinmarsh** [comment]
There's an approved PR https://github.com/jazzband/django-pipeline/pull/760 for this, just waiting for it to be merged and released (maybe @cyberdelia or @TheBuky will have some time?)

**Comment by markflorence728** [comment]
Thanks for your reply.
I am using django-pipeline package in our company projects. We started to
upgrade django4.0. We are waiting for new release version for django4.0
support.
Hope to get news as soon as possible.

Regards,
Joe

**Comment by TheBuky** [comment]
Thank for the PR and the support of Django 4.0

I have start to work on it last week, but I get some trouble documented as #765 with an old python package to minify JS. I will drop the support for `slimit`, we should past tests and the packages will be release.

**Comment by TheBuky** [comment]
All tests past after `slimit` removed but the [automated task](https://github.com/jazzband/django-pipeline/runs/4766034933) to push the release 2.0.8 failed... **File already exists.** 

I report the issue.

**Comment by TheBuky** [comment]
All tests past after `slimit` removed but the [automated task](https://github.com/jazzband/django-pipeline/runs/4766034933) to push the release 2.0.8 failed... **File already exists.** 

~~I report the issue.~~ 
Many thinks have change in Jazzband, now it's the project lead to see that. Can you look why an error @cyberdelia happen during the publishing process?

**Comment by cyberdelia** [comment]
@TheBuky Looks like it's conflicting with the previously unreleased 2.0.8 you did a few days ago, I removed that upload and re-released.

**Comment by TheBuky** [comment]
Oh my bad, I didn't think the previous unreleased version could block this one. Thank for fixing it!
The package is now on Pypi @markflorence728
