### ISSUE TITLE
Remove `manifesto` support

### ISSUE THREAD

**Issue by peymanslh** [jazzband/django-pipeline#783]
In the documentation, there is a section about [using `manifesto`](https://django-pipeline.readthedocs.io/en/latest/usage.html#cache-manifest) for caching manifest, and there is a file `pipeline/menifest.py` that uses this package. (which has an error because in line 3 the import is wrong)
 https://github.com/jazzband/django-pipeline/blob/24050e152f1ee3f27c5b14a00d19070142bf9d29/pipeline/manifest.py#L3

When I tried to use `manifesto`, it doesn't work and raised an error. The bug is in the `manifesto` from 2016. [link](https://github.com/cyberdelia/manifesto/issues/13)
I think with this situation its better to drop support for the manifesto package and remove it from code and documentation.
Related issues #508 .
I can make a PR for this if it's OK

**Comment by peymanslh** [comment]
@cyberdelia 
Can I have your opinion about this before sending a PR?

**Comment by cyberdelia** [comment]
Go ahead.
