### ISSUE TITLE
Support for Django 4.2 

### ISSUE THREAD

**Issue by kostasgan12** [jazzband/django-pipeline#797]
Hello, 

Is there an estimation regarding the django-pipeline release supporting Django 4.2?

**Comment by peymanslh** [comment]
Hi,
Currently `django-pipeline` supports Django 4.2 but we didn't have a release for that,
Do you have any problems with `django-pipeline` and Django 4.2?

**Comment by kostasgan12** [comment]
> Hi,
> 
> Currently `django-pipeline` supports Django 4.2 but we didn't have a release for that,
> 
> Do you have any issues with `django-pipeline` and Django 4.2?

Thank you for your prompt response. No, I haven't run into any issues so far.

**Comment by peymanslh** [comment]
Fixed in #793 and deployed in #804
