### ISSUE TITLE
Can JavaScript function() {} wrapper be optional?

### ISSUE THREAD

**Issue by chipx86** [jazzband/django-pipeline#96]
Now that everything's working great with the new branch, I've encountered the new `(function() { ... })` wrapper around all compressed JavaScript.

I understand the purpose of doing this. Not polluting the global namespace is generally nice. However, in my case, I want to, and I'd rather have the control over which files pollute and which don't. Can this feature be optional? At the moment, we're quite broken with this enabled.

**Comment by Blender3D** [comment]
Can you make it changeable? I'd like to wrap my JS in something else.
